default_platform(:ios)

platform :ios do
	desc "Push a new dev build to AppCenter"
	lane :dev do
		increment_build_number_in_plist(
			scheme: "Autonomy Dev")

		update_info_plist(
			plist_path: "./Autonomy/InfoPlist/Dev-Info.plist",
			block: proc do |plist|
				appCredential = plist["AppCredentials"]
				appCredential["API_SERVER_URL"] = ENV["TEST_SERVER_URL"]
				appCredential["GOOGLE_API_KEY"] = ENV["GOOGLE_API_KEY"]
			end
			)

		cert(generate_apple_certs: false)
		sigh(force: true,
			 adhoc: true)

		build_app(
			scheme: "Autonomy Dev",
			export_method: "ad-hoc",
			workspace: "Autonomy.xcworkspace",
			include_bitcode: false,
			clean: true,
			output_directory: "./ipas")

		sentry_upload_dsym(
			auth_token: ENV['SENTRY_AUTH_TOKEN'],
			org_slug: 'bitmark-inc',
			project_slug: 'autonomy-ios',
			dsym_path: './ipas/Autonomy.app.dSYM.zip')

		appcenter_upload(
			api_token: ENV["APPCENTER_API_TOKEN"],
			owner_name: "support-zzd0-28",
			owner_type: "organization",
			app_name: "Autonomy",
			notify_testers: true)
	end

	desc "Push a new inhouse build to AppCenter"
	lane :inhouse do
		increment_build_number_in_plist(
			scheme: "Autonomy Inhouse")

		update_info_plist(
			plist_path: "./Autonomy/InfoPlist/Inhouse-Info.plist",
			block: proc do |plist|
				appCredential = plist["AppCredentials"]
				appCredential["API_SERVER_URL"] = ENV["SERVER_URL"]
				appCredential["GOOGLE_API_KEY"] = ENV["GOOGLE_API_KEY"]
			end
			)

		cert
		sigh(force: true)

		build_app(
			scheme: "Autonomy Inhouse",
			export_method: "enterprise",
			workspace: "Autonomy.xcworkspace",
			include_bitcode: false,
			clean: false,
			output_directory: "./ipas")

		sentry_upload_dsym(
			auth_token: ENV['SENTRY_AUTH_TOKEN'],
			org_slug: 'bitmark-inc',
			project_slug: 'autonomy-ios',
			dsym_path: './ipas/Autonomy.app.dSYM.zip'
		)

		appcenter_upload(
			api_token: ENV["APPCENTER_API_TOKEN"],
			owner_name: "support-zzd0-28",
			owner_type: "organization",
			app_name: "Autonomy-Inhouse",
			notify_testers: true
		)
	end
end
